from pydantic import BaseModel, Field
from typing import Optional, List

from langchain_core.documents import Document


class RagState(BaseModel):
    # user_query: Optional[str] | None = Field(
    #     default=None,
    #     description="(deprecated) query text for vector DB retrieval generated by LLM",
    #     deprecated=True,
    # )
    # user_query_embedding: Optional[List[float]] = Field(
    #     default_factory=list,
    #     description="(deprecated) user_query를 임베딩한 벡터 값",
    #     deprecated=True,
    # )
    query_texts: Optional[List[str]] = Field(
        default_factory=list,
        description="query texts for vector DB retrieval generated by LLM",
    )  # 각 건강 정보별로 질문을 생성한 경우
    query_texts_embeddings: Optional[List[List[float]]] = Field(
        default_factory=list,
        description="query_texts 각각을 임베딩한 벡터 목록",
    )  # 각 건강 정보별로 질문을 생성한 경우
    terms_normal_tag_dense: Optional[List[Document]] = Field(
        default_factory=list,
        description="terms_normal_tag_dense 컬렉션에서 검색한 결과",
    )
    terms_normal_tag_dense_unfiltered: Optional[List[Document]] = Field(
        default_factory=list,
        description="terms_normal_tag_dense 컬렉션에서 filter 미적용 검색 결과",
    )
    terms_simple_tag_dense: Optional[List[Document]] = Field(
        default_factory=list,
        description="terms_simple_tag_dense 컬렉션에서 검색한 결과",
    )
    terms_simple_tag_dense_unfiltered: Optional[List[Document]] = Field(
        default_factory=list,
        description="terms_simple_tag_dense 컬렉션에서 filter 미적용 검색 결과",
    )
    retrieved_documents: Optional[List[Document]] = Field(
        default_factory=list,
        description="평가/정렬 후 최종 취합된 검색 결과",
    )


class GenerateQueryTextOutput(BaseModel):
    query_text: str = Field(
        description="주어진 정보를 바탕으로 LLM이 생성한 사용자 질문"
    )
